-- Generated by `php setup.php --dump-sql`. Safe to run repeatedly.

CREATE TABLE IF NOT EXISTS settings (
        setting_key   VARCHAR(64) NOT NULL PRIMARY KEY,
        setting_value VARCHAR(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS roads (
        id            INTEGER NOT NULL PRIMARY KEY,
        name          VARCHAR(80) NOT NULL,
        green_seconds INTEGER NOT NULL DEFAULT 120,
        enabled       TINYINT NOT NULL DEFAULT 1,
        sort_order    INTEGER NOT NULL DEFAULT 0
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rules (
        id             INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name           VARCHAR(120) NOT NULL,
        road_id        INTEGER NULL,
        days           VARCHAR(20) NOT NULL DEFAULT '1,2,3,4,5,6,7',
        start_time     CHAR(5) NOT NULL,
        end_time       CHAR(5) NOT NULL,
        adjust_seconds INTEGER NOT NULL,
        active         TINYINT NOT NULL DEFAULT 1
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS signal_state (
        id          INTEGER NOT NULL PRIMARY KEY,
        mode        VARCHAR(16) NOT NULL DEFAULT 'auto',
        hold_road   INTEGER NOT NULL DEFAULT 0,
        phase_road  INTEGER NOT NULL DEFAULT 0,
        phase_type  VARCHAR(8) NOT NULL DEFAULT 'red',
        started_ms  BIGINT NOT NULL DEFAULT 0,
        duration_ms BIGINT NOT NULL DEFAULT 0
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
        id            INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        username      VARCHAR(64) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        created_at    DATETIME NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
        id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        username   VARCHAR(64) NOT NULL,
        action     VARCHAR(64) NOT NULL,
        detail     VARCHAR(255) NOT NULL DEFAULT '',
        created_at DATETIME NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Default settings and the four roads
INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('default_green_seconds', '120');
INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('orange_seconds', '4');
INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('all_red_seconds', '2');
INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('min_green_seconds', '10');
INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('max_green_seconds', '600');
INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('step_seconds', '15');
INSERT IGNORE INTO roads (id, name, green_seconds, enabled, sort_order) VALUES (1, 'Road 1', 120, 1, 1);
INSERT IGNORE INTO roads (id, name, green_seconds, enabled, sort_order) VALUES (2, 'Road 2', 120, 1, 2);
INSERT IGNORE INTO roads (id, name, green_seconds, enabled, sort_order) VALUES (3, 'Road 3', 120, 1, 3);
INSERT IGNORE INTO roads (id, name, green_seconds, enabled, sort_order) VALUES (4, 'Road 4', 120, 1, 4);
INSERT IGNORE INTO signal_state (id, mode) VALUES (1, 'auto');
-- Create the first admin with: php setup.php --user=admin --pass=...
