<?php
// CLI installer:
//   php setup.php                         create tables + seed 4 roads, and an admin user
//   php setup.php --user=ops --pass=...   choose the admin credentials (otherwise a random password is printed)
//   php setup.php --dump-sql              print the MySQL schema (used to generate schema.sql)
if (PHP_SAPI !== 'cli') { exit('Run from the command line.'); }
require __DIR__ . '/src/bootstrap.php';
require __DIR__ . '/src/auth.php';

$opts = getopt('', ['user::', 'pass::', 'dump-sql']);

if (isset($opts['dump-sql'])) {
    echo "-- Generated by `php setup.php --dump-sql`. Safe to run repeatedly.\n\n";
    foreach (schema_statements('mysql') as $sql) {
        echo preg_replace('/\n {4}/', "\n", $sql) . ";\n\n";
    }
    echo "-- Default settings and the four roads\n";
    foreach (DEFAULT_SETTINGS as $k => $v) {
        echo "INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('$k', '$v');\n";
    }
    for ($i = 1; $i <= 4; $i++) {
        echo "INSERT IGNORE INTO roads (id, name, green_seconds, enabled, sort_order) VALUES ($i, 'Road $i', 120, 1, $i);\n";
    }
    echo "INSERT IGNORE INTO signal_state (id, mode) VALUES (1, 'auto');\n";
    echo "-- Create the first admin with: php setup.php --user=admin --pass=...\n";
    exit;
}

$pdo = db();
install_schema($pdo, db_driver($pdo));
echo "Tables ready.\n";

if (!(int) $pdo->query('SELECT COUNT(*) FROM users')->fetchColumn()) {
    $user = $opts['user'] ?? 'admin';
    $pass = $opts['pass'] ?? bin2hex(random_bytes(6));
    create_user($pdo, $user, $pass);
    echo "Admin user created.\n  username: $user\n  password: $pass\n  (change it in the admin page)\n";
} else {
    echo "Admin user already exists; left unchanged.\n";
}
